#!/usr/bin/env python3
"""
Invoice Generator — Country Gardens Farm Market (Thanksgiving Pie Fundraiser 2026)
Generated by the invoice-creator skill, customized for order-form pickup/delivery data.
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle,
    Paragraph, Spacer, Image, HRFlowable
)
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, 'output')

VENDOR = {
    "name":      "Country Gardens Farm Market",
    "address":   "42 Robbinsville-Edinburg Road, Robbinsville, NJ 08691",
    "phone":     "(609) 259-1221",
    "email":     "cgfmfundraising@gmail.com",
    "logo_path": os.path.join(HERE, 'logo.jpg'),
}

INVOICE = {
    'num': 'INV-2026-004',
    'date': 'September 26, 2026',
    'customer': 'Carta',
    'contact_name': 'Resse Petagna',
    'contact_phone': '(555) 555-5555',
    'contact_email': 'contact@example.com',
    'fulfillment': 'Delivery',
    'fulfillment_date': 'Tuesday, 11/24/2026',
    'fulfillment_time': '10:00 AM',
    'delivery_address': '17 Chippin Ct, Robbinsville, NJ 08691',
    'sections': [
        ('Fresh Baked Pies ($17.00 each — fundraiser rate)', [
            ('Apple', 3, 17.00),
            ('Apple Crumb', 5, 17.00),
            ('Apple Caramel Walnut', 1, 17.00),
            ('Blueberry Crumb', 1, 17.00),
            ('Lemon Crumb', 8, 17.00),
            ('Pumpkin', 9, 17.00),
            ('Banana Cream', 4, 17.00),
            ('Key Lime West', 2, 17.00),
            ('Pecan', 3, 17.00),
            ('No Sugar Added Apple', 1, 17.00),
        ]),
        ('Apple Cider Donuts', [
            ('Apple Cider Donuts (pack of 5)', 10, 7.00),
        ]),
        ('Delivery', [
            ('Delivery Charge', 1, 100.00),
        ]),
    ],
}

DK_GREEN  = colors.HexColor('#1b4a1b')
MD_GREEN  = colors.HexColor('#2e7d2e')
LT_GREEN  = colors.HexColor('#eaf5ea')
STRIPE    = colors.HexColor('#f5faf5')
GRAY_LINE = colors.HexColor('#cccccc')
GRAY_TEXT = colors.HexColor('#666666')

def p(text, fn='Helvetica', sz=9, color=colors.black, align=TA_LEFT):
    return Paragraph(text, ParagraphStyle(
        'x', fontName=fn, fontSize=sz, textColor=color,
        alignment=align, leading=max(sz + 3, 11),
        spaceAfter=0, spaceBefore=0
    ))

def pb(text, **kw): return p(text, fn='Helvetica-Bold', **kw)

def build_invoice(inv, vendor):
    fname = os.path.join(OUT_DIR, f'Invoice_{inv["num"]}.pdf')
    doc = SimpleDocTemplate(
        fname, pagesize=letter,
        leftMargin=0.42*inch, rightMargin=0.42*inch,
        topMargin=0.38*inch,  bottomMargin=0.38*inch,
        pageCompression=1,
    )
    W = letter[0] - 0.84*inch
    story = []

    logo = Image(vendor['logo_path'], width=1.76*inch, height=1.76*inch * 300 / 440)
    hdr_right = Table([
        [pb('INVOICE', sz=22, color=DK_GREEN, align=TA_RIGHT)],
        [p(f'Date: {inv["date"]}',     sz=8, color=GRAY_TEXT, align=TA_RIGHT)],
        [p(f'Invoice #: {inv["num"]}', sz=8, color=GRAY_TEXT, align=TA_RIGHT)],
    ], colWidths=[W - 1.82*inch])
    hdr_right.setStyle(TableStyle([
        ('TOPPADDING',    (0, 0), (-1, -1), 1),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 1),
    ]))
    hdr = Table([[logo, hdr_right]], colWidths=[1.82*inch, W - 1.82*inch])
    hdr.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'MIDDLE')]))
    story.append(hdr)
    story.append(HRFlowable(width='100%', thickness=2, color=DK_GREEN,
                             spaceAfter=4, spaceBefore=3))

    # BILL TO / CONTACT / FULFILLMENT
    bill = Table([
        [pb('ORGANIZATION',   sz=8, color=DK_GREEN),
         pb('CONTACT',        sz=8, color=DK_GREEN),
         pb('DELIVERY / PICKUP', sz=8, color=DK_GREEN)],
        [pb(inv['customer'], sz=11),
         p(inv['contact_name'], sz=9),
         p(inv['fulfillment'], sz=9)],
        ['',
         p(inv['contact_phone'], sz=9),
         p(f'Date: {inv["fulfillment_date"]}', sz=9)],
        ['',
         p(inv['contact_email'], sz=9),
         p(f'Time: {inv["fulfillment_time"]}', sz=9)],
        ['', '',
         p(f'Address: {inv["delivery_address"]}', sz=9)],
    ], colWidths=[W * 0.30, W * 0.32, W * 0.38])
    bill.setStyle(TableStyle([
        ('VALIGN',        (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING',    (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))
    story.append(bill)
    story.append(HRFlowable(width='100%', thickness=1, color=GRAY_LINE,
                             spaceAfter=4, spaceBefore=4))

    CW = [W - 2.3*inch, 0.5*inch, 0.95*inch, 0.85*inch]

    rows = [[
        pb('Item',       sz=9, color=colors.white),
        pb('Qty',        sz=9, color=colors.white, align=TA_CENTER),
        pb('Unit Price', sz=9, color=colors.white, align=TA_RIGHT),
        pb('Amount',     sz=9, color=colors.white, align=TA_RIGHT),
    ]]
    ts = [
        ('BACKGROUND',    (0, 0), (-1, 0), DK_GREEN),
        ('TOPPADDING',    (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
        ('ALIGN',         (1, 0), (1,  -1), 'CENTER'),
        ('ALIGN',         (2, 0), (3,  -1), 'RIGHT'),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
        ('FONTSIZE',      (0, 0), (-1, -1), 8),
    ]

    ri = 1
    grand = 0.0

    for sec_name, items in inv['sections']:
        rows.append([pb(sec_name, sz=8, color=colors.white), '', '', ''])
        ts += [
            ('BACKGROUND',    (0, ri), (-1, ri), MD_GREEN),
            ('SPAN',          (0, ri), (-1, ri)),
            ('TOPPADDING',    (0, ri), (-1, ri), 3),
            ('BOTTOMPADDING', (0, ri), (-1, ri), 3),
        ]
        ri += 1
        for idx, (desc, qty, price) in enumerate(items):
            amt = qty * price
            grand += amt
            bg = STRIPE if idx % 2 == 0 else colors.white
            rows.append([p(desc, sz=8), str(qty), f'${price:.2f}', f'${amt:.2f}'])
            ts.append(('BACKGROUND', (0, ri), (-1, ri), bg))
            ri += 1

    tbl = Table(rows, colWidths=CW)
    tbl.setStyle(TableStyle(ts))
    story.append(tbl)

    gt = Table([[
        pb('GRAND TOTAL', sz=11, color=DK_GREEN, align=TA_RIGHT), '', '',
        pb(f'${grand:,.2f}', sz=11, color=DK_GREEN, align=TA_RIGHT),
    ]], colWidths=CW)
    gt.setStyle(TableStyle([
        ('SPAN',          (0, 0), (2, 0)),
        ('BACKGROUND',    (0, 0), (-1, 0), LT_GREEN),
        ('LINEABOVE',     (0, 0), (-1, 0), 2, DK_GREEN),
        ('LINEBELOW',     (0, 0), (-1, 0), 2, DK_GREEN),
        ('TOPPADDING',    (0, 0), (-1, 0), 6),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
    ]))
    story.append(gt)
    story.append(Spacer(1, 0.1*inch))

    story.append(p(
        'ALL PAYMENTS MUST BE MADE VIA CASH OR CHECK.', sz=9, fn='Helvetica-Bold', color=colors.HexColor('#b00000')
    ))
    story.append(Spacer(1, 0.1*inch))
    SIG_BG = colors.HexColor('#fff9c4')
    SIG_BORDER = colors.HexColor('#e0b800')
    sig = Table([
        [pb('CUSTOMER SIGNATURE REQUIRED', sz=9, color=DK_GREEN), '', ''],
        [p('My signature below confirms that these amounts are final and cannot be changed once submitted.',
           sz=8, color=colors.HexColor('#444444')), '', ''],
        ['', '', ''],
        [p('_' * 36, sz=9), p('_' * 28, sz=9), p('_' * 14, sz=9)],
        [p('Customer Signature', sz=7, color=GRAY_TEXT),
         p('Printed Name',       sz=7, color=GRAY_TEXT),
         p('Date',               sz=7, color=GRAY_TEXT)],
    ], colWidths=[W * 0.43, W * 0.37, W * 0.20], rowHeights=[None, None, 0.16*inch, None, None])
    sig.setStyle(TableStyle([
        ('SPAN',          (0, 0), (-1, 0)),
        ('SPAN',          (0, 1), (-1, 1)),
        ('BACKGROUND',    (0, 0), (-1, -1), SIG_BG),
        ('BOX',           (0, 0), (-1, -1), 1.5, SIG_BORDER),
        ('LEFTPADDING',   (0, 0), (-1, -1), 8),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 8),
        ('TOPPADDING',    (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
        ('TOPPADDING',    (0, 0), (-1, 0), 7),
        ('BOTTOMPADDING', (0, -1), (-1, -1), 7),
    ]))
    story.append(sig)

    story.append(Spacer(1, 0.06*inch))
    story.append(HRFlowable(width='100%', thickness=0.5, color=GRAY_LINE, spaceAfter=3))
    story.append(p(
        f'{vendor["name"]}  •  {vendor["address"]}  •  {vendor["phone"]}  •  {vendor["email"]}',
        sz=7, color=GRAY_TEXT, align=TA_CENTER
    ))

    doc.build(story)
    return fname, grand

if __name__ == '__main__':
    os.makedirs(OUT_DIR, exist_ok=True)
    path, total = build_invoice(INVOICE, VENDOR)
    print(f'{path}  ${total:,.2f}')
